### ISSUE TITLE
단체 소개 페이지 삽입

### ISSUE THREAD

**Issue by kswgit** [kswgit/shyA-front#6]
@4335139042b20dea4314e485fd1ea36b88d910b8

**Comment by kswgit** [comment]
스켈레톤 css

@d5b4b25c291a3949a8953421496ca5c4f10945d4

**Comment by vbalien** [comment]
커밋메시지에 #6 붙이면 여기에 커밋 자동으로 표시됨. (# 뒤에 이슈번호)

**Comment by kswgit** [comment]
초안 만들어봄

@2575697e8d844ca423550c75c1bd2434e1d001d5

**Comment by kswgit** [comment]
@vbalien 개쩌넴
